## 외부 서비스 관련 문제

외부 서비스는 말그대로 외부의 서비스이기에 에러 처리에 더 신경 써주어야 한다.

우리 서비스가 사용하는 외부 서비스는 idp 서버 그리고 iptime 이다. (아직 iptime 관련 예외 문제는 고민중이다.)

아래 코드는 idp 서버에서 토큰과 userId를 통해 유저의 정보를 조회하는 코드이다.

기본적으로 fegin을 사용하여 circuit breaker를 설정할 수 있다.

이는 대상 서버에 장애가 일어났을 때를 대비한 것이다.

우리는 이와 더불어 잘못된 요청을 보냈을 때에 대한 대비도 하여야 한다.

이를 대비한 것이 아래 코드이다.

잘못된 요청을 한다면 UserInfo에 맞는 정보를 반환하지 않을 것이다.

그렇다면 exception이 일어날 것이고 우리는 이를 catch 하여 우리 서비스에 맞도록 exception을 재정의 해주면 된다.

```java
    @Override
    public UserInfoVO getUserByToken(String accessToken) {
        try {
            return feignUserInfo.getUserInfoByToken(accessToken);
        } catch (Exception e) {
            throw new OuterServiceValidateException(OuterServiceException.IDP_EXCEPTION);
        }
    }

    @Override
    public UserInfoVO getUserById(Long userId) {
        Optional<User> userByAccessToken = repository.findByUserId(userId);

        if (userByAccessToken.isPresent()) {
            return userByAccessToken
                .get()
                .getUserInfoVO();
        }

        try {
            UserInfoVO userInfo = feignUserInfo.getUserInfo(userId);

            User user = new User(userInfo);

            repository.save(user);

            return userInfo;
        } catch (Exception e) {
            throw new OuterServiceValidateException(OuterServiceException.IDP_EXCEPTION);
        }
    }
```